version: 2
updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      timezone: "Asia/Kolkata"
      interval: weekly
      day: saturday
      time: "00:00"
    labels:
      - "notion dependencies"
    allow:
      - dependency-name: "react*"
      - dependency-name: "next*"
      - dependency-name: "notion*"
      - dependency-name: "@notionhq/client"
