version: 2
updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      timezone: 05:00 UTC
      interval: weekly
      day: saturday
      time: 0:00
    labels:
      - "notion dependencies"
    allow:
      - dependency-name: "react*"
      - dependency-name: "next*"
      - dependency-name: "notion*"
      - dependency-name: "@notionhq/client"